# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface_framework.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1050, 805)
        Form.setMinimumSize(QtCore.QSize(1050, 805))
        Form.setMaximumSize(QtCore.QSize(1050, 805))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setStyleSheet("background-color: rgb(67, 67, 67);")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_8 = QtWidgets.QWidget(self.widget_2)
        self.widget_8.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_2.addWidget(self.widget_8, 0, 2, 2, 1)
        self.widget_7 = QtWidgets.QWidget(self.widget_2)
        self.widget_7.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_2.addWidget(self.widget_7, 0, 0, 2, 1)
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_4.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_4.setSpacing(2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Btn_RESET = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_RESET.sizePolicy().hasHeightForWidth())
        self.Btn_RESET.setSizePolicy(sizePolicy)
        self.Btn_RESET.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_RESET.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Btn_RESET.setFont(font)
        self.Btn_RESET.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Btn_RESET.setObjectName("Btn_RESET")
        self.gridLayout_4.addWidget(self.Btn_RESET, 0, 0, 1, 1)
        self.Btn_O = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_O.sizePolicy().hasHeightForWidth())
        self.Btn_O.setSizePolicy(sizePolicy)
        self.Btn_O.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_O.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_O.setStyleSheet("background-color: rgb(167, 167, 167);\n"
"image: url(:/framework/images/O_Btn.png);")
        self.Btn_O.setText("")
        self.Btn_O.setObjectName("Btn_O")
        self.gridLayout_4.addWidget(self.Btn_O, 0, 1, 1, 1)
        self.Btn_N = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_N.sizePolicy().hasHeightForWidth())
        self.Btn_N.setSizePolicy(sizePolicy)
        self.Btn_N.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_N.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_N.setStyleSheet("background-color: rgb(167, 167, 167);\n"
"image: url(:/framework/images/N_Btn.png);")
        self.Btn_N.setText("")
        self.Btn_N.setObjectName("Btn_N")
        self.gridLayout_4.addWidget(self.Btn_N, 0, 2, 1, 1)
        self.Btn_G = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_G.sizePolicy().hasHeightForWidth())
        self.Btn_G.setSizePolicy(sizePolicy)
        self.Btn_G.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_G.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_G.setStyleSheet("background-color: rgb(167, 167, 167);\n"
"image: url(:/framework/images/G_Btn.png);")
        self.Btn_G.setText("")
        self.Btn_G.setObjectName("Btn_G")
        self.gridLayout_4.addWidget(self.Btn_G, 0, 3, 1, 1)
        self.Btn_P = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_P.sizePolicy().hasHeightForWidth())
        self.Btn_P.setSizePolicy(sizePolicy)
        self.Btn_P.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_P.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_P.setStyleSheet("background-color: rgb(167, 167, 167);\n"
"image: url(:/framework/images/P_Btn.png);")
        self.Btn_P.setText("")
        self.Btn_P.setObjectName("Btn_P")
        self.gridLayout_4.addWidget(self.Btn_P, 0, 4, 1, 1)
        self.Btn_7 = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_7.sizePolicy().hasHeightForWidth())
        self.Btn_7.setSizePolicy(sizePolicy)
        self.Btn_7.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_7.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_7.setStyleSheet("background-color: rgb(167, 167, 167);\n"
"image: url(:/framework/images/7_Btn.png);")
        self.Btn_7.setText("")
        self.Btn_7.setObjectName("Btn_7")
        self.gridLayout_4.addWidget(self.Btn_7, 0, 5, 1, 1)
        self.Btn_8 = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_8.sizePolicy().hasHeightForWidth())
        self.Btn_8.setSizePolicy(sizePolicy)
        self.Btn_8.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_8.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_8.setStyleSheet("background-color: rgb(167, 167, 167);\n"
"image: url(:/framework/images/8_Btn.png);")
        self.Btn_8.setText("")
        self.Btn_8.setObjectName("Btn_8")
        self.gridLayout_4.addWidget(self.Btn_8, 0, 6, 1, 1)
        self.Btn_9 = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_9.sizePolicy().hasHeightForWidth())
        self.Btn_9.setSizePolicy(sizePolicy)
        self.Btn_9.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_9.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_9.setStyleSheet("background-color: rgb(167, 167, 167);\n"
"image: url(:/framework/images/9_Btn.png);")
        self.Btn_9.setText("")
        self.Btn_9.setObjectName("Btn_9")
        self.gridLayout_4.addWidget(self.Btn_9, 0, 7, 1, 1)
        self.Btn_ALTER = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_ALTER.sizePolicy().hasHeightForWidth())
        self.Btn_ALTER.setSizePolicy(sizePolicy)
        self.Btn_ALTER.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_ALTER.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Btn_ALTER.setFont(font)
        self.Btn_ALTER.setStyleSheet("background-color: rgb(160, 130, 90);\n"
"")
        self.Btn_ALTER.setObjectName("Btn_ALTER")
        self.gridLayout_4.addWidget(self.Btn_ALTER, 0, 8, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_22.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_22.sizePolicy().hasHeightForWidth())
        self.pushButton_22.setSizePolicy(sizePolicy)
        self.pushButton_22.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_22.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_22.setStyleSheet("background-color: rgb(167, 167, 167);")
        self.pushButton_22.setText("")
        self.pushButton_22.setFlat(True)
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout_4.addWidget(self.pushButton_22, 1, 0, 1, 1)
        self.Btn_X = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_X.sizePolicy().hasHeightForWidth())
        self.Btn_X.setSizePolicy(sizePolicy)
        self.Btn_X.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_X.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_X.setStyleSheet("background-color: rgb(167, 167, 167);\n"
"image: url(:/framework/images/X_Btn.png);")
        self.Btn_X.setText("")
        self.Btn_X.setObjectName("Btn_X")
        self.gridLayout_4.addWidget(self.Btn_X, 1, 1, 1, 1)
        self.Btn_Y = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_Y.sizePolicy().hasHeightForWidth())
        self.Btn_Y.setSizePolicy(sizePolicy)
        self.Btn_Y.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_Y.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_Y.setStyleSheet("background-color: rgb(167, 167, 167);\n"
"image: url(:/framework/images/Y_Btn.png);")
        self.Btn_Y.setText("")
        self.Btn_Y.setObjectName("Btn_Y")
        self.gridLayout_4.addWidget(self.Btn_Y, 1, 2, 1, 1)
        self.Btn_Z = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_Z.sizePolicy().hasHeightForWidth())
        self.Btn_Z.setSizePolicy(sizePolicy)
        self.Btn_Z.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_Z.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_Z.setStyleSheet("background-color: rgb(167, 167, 167);\n"
"image: url(:/framework/images/Z_Btn.png);")
        self.Btn_Z.setText("")
        self.Btn_Z.setObjectName("Btn_Z")
        self.gridLayout_4.addWidget(self.Btn_Z, 1, 3, 1, 1)
        self.Btn_Q = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_Q.sizePolicy().hasHeightForWidth())
        self.Btn_Q.setSizePolicy(sizePolicy)
        self.Btn_Q.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_Q.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_Q.setStyleSheet("background-color: rgb(167, 167, 167);\n"
"image: url(:/framework/images/Q_Btn.png);")
        self.Btn_Q.setText("")
        self.Btn_Q.setObjectName("Btn_Q")
        self.gridLayout_4.addWidget(self.Btn_Q, 1, 4, 1, 1)
        self.Btn_4 = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_4.sizePolicy().hasHeightForWidth())
        self.Btn_4.setSizePolicy(sizePolicy)
        self.Btn_4.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_4.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_4.setStyleSheet("background-color: rgb(167, 167, 167);\n"
"image: url(:/framework/images/4_Btn.png);")
        self.Btn_4.setText("")
        self.Btn_4.setObjectName("Btn_4")
        self.gridLayout_4.addWidget(self.Btn_4, 1, 5, 1, 1)
        self.Btn_5 = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_5.sizePolicy().hasHeightForWidth())
        self.Btn_5.setSizePolicy(sizePolicy)
        self.Btn_5.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_5.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_5.setStyleSheet("background-color: rgb(167, 167, 167);\n"
"image: url(:/framework/images/5_Btn.png);")
        self.Btn_5.setText("")
        self.Btn_5.setObjectName("Btn_5")
        self.gridLayout_4.addWidget(self.Btn_5, 1, 6, 1, 1)
        self.Btn_6 = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_6.sizePolicy().hasHeightForWidth())
        self.Btn_6.setSizePolicy(sizePolicy)
        self.Btn_6.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_6.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_6.setStyleSheet("background-color: rgb(167, 167, 167);\n"
"image: url(:/framework/images/6_Btn.png);")
        self.Btn_6.setText("")
        self.Btn_6.setObjectName("Btn_6")
        self.gridLayout_4.addWidget(self.Btn_6, 1, 7, 1, 1)
        self.Btn_INSERT = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_INSERT.sizePolicy().hasHeightForWidth())
        self.Btn_INSERT.setSizePolicy(sizePolicy)
        self.Btn_INSERT.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_INSERT.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_INSERT.setFont(font)
        self.Btn_INSERT.setStyleSheet("background-color: rgb(160, 130, 90);\n"
"")
        self.Btn_INSERT.setObjectName("Btn_INSERT")
        self.gridLayout_4.addWidget(self.Btn_INSERT, 1, 8, 1, 1)
        self.Btn_I = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_I.sizePolicy().hasHeightForWidth())
        self.Btn_I.setSizePolicy(sizePolicy)
        self.Btn_I.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_I.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_I.setStyleSheet("background-color: rgb(167, 167, 167);\n"
"image: url(:/framework/images/I_Btn.png);")
        self.Btn_I.setText("")
        self.Btn_I.setObjectName("Btn_I")
        self.gridLayout_4.addWidget(self.Btn_I, 2, 1, 1, 1)
        self.Btn_J = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_J.sizePolicy().hasHeightForWidth())
        self.Btn_J.setSizePolicy(sizePolicy)
        self.Btn_J.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_J.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_J.setStyleSheet("background-color: rgb(167, 167, 167);\n"
"image: url(:/framework/images/J_Btn.png);")
        self.Btn_J.setText("")
        self.Btn_J.setObjectName("Btn_J")
        self.gridLayout_4.addWidget(self.Btn_J, 2, 2, 1, 1)
        self.Btn_K = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_K.sizePolicy().hasHeightForWidth())
        self.Btn_K.setSizePolicy(sizePolicy)
        self.Btn_K.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_K.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_K.setStyleSheet("background-color: rgb(167, 167, 167);\n"
"image: url(:/framework/images/K_Btn.png);")
        self.Btn_K.setText("")
        self.Btn_K.setObjectName("Btn_K")
        self.gridLayout_4.addWidget(self.Btn_K, 2, 3, 1, 1)
        self.Btn_R = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_R.sizePolicy().hasHeightForWidth())
        self.Btn_R.setSizePolicy(sizePolicy)
        self.Btn_R.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_R.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_R.setStyleSheet("background-color: rgb(167, 167, 167);\n"
"image: url(:/framework/images/R_Btn.png);")
        self.Btn_R.setText("")
        self.Btn_R.setObjectName("Btn_R")
        self.gridLayout_4.addWidget(self.Btn_R, 2, 4, 1, 1)
        self.Btn_1 = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_1.sizePolicy().hasHeightForWidth())
        self.Btn_1.setSizePolicy(sizePolicy)
        self.Btn_1.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_1.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_1.setStyleSheet("background-color: rgb(167, 167, 167);\n"
"image: url(:/framework/images/1_Btn.png);")
        self.Btn_1.setText("")
        self.Btn_1.setObjectName("Btn_1")
        self.gridLayout_4.addWidget(self.Btn_1, 2, 5, 1, 1)
        self.Btn_2 = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_2.sizePolicy().hasHeightForWidth())
        self.Btn_2.setSizePolicy(sizePolicy)
        self.Btn_2.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_2.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_2.setStyleSheet("background-color: rgb(167, 167, 167);\n"
"image: url(:/framework/images/2_Btn.png);")
        self.Btn_2.setText("")
        self.Btn_2.setObjectName("Btn_2")
        self.gridLayout_4.addWidget(self.Btn_2, 2, 6, 1, 1)
        self.Btn_3 = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_3.sizePolicy().hasHeightForWidth())
        self.Btn_3.setSizePolicy(sizePolicy)
        self.Btn_3.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_3.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_3.setStyleSheet("background-color: rgb(167, 167, 167);\n"
"image: url(:/framework/images/3_Btn.png);")
        self.Btn_3.setText("")
        self.Btn_3.setObjectName("Btn_3")
        self.gridLayout_4.addWidget(self.Btn_3, 2, 7, 1, 1)
        self.Btn_DELETE = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_DELETE.sizePolicy().hasHeightForWidth())
        self.Btn_DELETE.setSizePolicy(sizePolicy)
        self.Btn_DELETE.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_DELETE.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_DELETE.setFont(font)
        self.Btn_DELETE.setStyleSheet("background-color: rgb(160, 130, 90);\n"
"")
        self.Btn_DELETE.setObjectName("Btn_DELETE")
        self.gridLayout_4.addWidget(self.Btn_DELETE, 2, 8, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_24.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_24.sizePolicy().hasHeightForWidth())
        self.pushButton_24.setSizePolicy(sizePolicy)
        self.pushButton_24.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_24.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_24.setStyleSheet("background-color: rgb(167, 167, 167);")
        self.pushButton_24.setText("")
        self.pushButton_24.setFlat(True)
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout_4.addWidget(self.pushButton_24, 3, 0, 1, 1)
        self.Btn_M = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_M.sizePolicy().hasHeightForWidth())
        self.Btn_M.setSizePolicy(sizePolicy)
        self.Btn_M.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_M.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_M.setStyleSheet("background-color: rgb(167, 167, 167);\n"
"image: url(:/framework/images/M_Btn.png);")
        self.Btn_M.setText("")
        self.Btn_M.setObjectName("Btn_M")
        self.gridLayout_4.addWidget(self.Btn_M, 3, 1, 1, 1)
        self.Btn_S = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_S.sizePolicy().hasHeightForWidth())
        self.Btn_S.setSizePolicy(sizePolicy)
        self.Btn_S.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_S.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_S.setStyleSheet("background-color: rgb(167, 167, 167);\n"
"image: url(:/framework/images/S_Btn.png);")
        self.Btn_S.setText("")
        self.Btn_S.setObjectName("Btn_S")
        self.gridLayout_4.addWidget(self.Btn_S, 3, 2, 1, 1)
        self.Btn_T = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_T.sizePolicy().hasHeightForWidth())
        self.Btn_T.setSizePolicy(sizePolicy)
        self.Btn_T.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_T.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_T.setStyleSheet("background-color: rgb(167, 167, 167);\n"
"image: url(:/framework/images/T_Btn.png);")
        self.Btn_T.setText("")
        self.Btn_T.setObjectName("Btn_T")
        self.gridLayout_4.addWidget(self.Btn_T, 3, 3, 1, 1)
        self.Btn_L = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_L.sizePolicy().hasHeightForWidth())
        self.Btn_L.setSizePolicy(sizePolicy)
        self.Btn_L.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_L.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_L.setStyleSheet("background-color: rgb(167, 167, 167);\n"
"image: url(:/framework/images/L_Btn.png);")
        self.Btn_L.setText("")
        self.Btn_L.setObjectName("Btn_L")
        self.gridLayout_4.addWidget(self.Btn_L, 3, 4, 1, 1)
        self.Btn_Minus = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_Minus.sizePolicy().hasHeightForWidth())
        self.Btn_Minus.setSizePolicy(sizePolicy)
        self.Btn_Minus.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_Minus.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Minus.setFont(font)
        self.Btn_Minus.setStyleSheet("background-color: rgb(167, 167, 167);")
        self.Btn_Minus.setObjectName("Btn_Minus")
        self.gridLayout_4.addWidget(self.Btn_Minus, 3, 5, 1, 1)
        self.Btn_0 = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_0.sizePolicy().hasHeightForWidth())
        self.Btn_0.setSizePolicy(sizePolicy)
        self.Btn_0.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_0.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_0.setFont(font)
        self.Btn_0.setStyleSheet("background-color: rgb(167, 167, 167);")
        self.Btn_0.setObjectName("Btn_0")
        self.gridLayout_4.addWidget(self.Btn_0, 3, 6, 1, 1)
        self.Btn_Dot = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_Dot.sizePolicy().hasHeightForWidth())
        self.Btn_Dot.setSizePolicy(sizePolicy)
        self.Btn_Dot.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_Dot.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Dot.setFont(font)
        self.Btn_Dot.setStyleSheet("background-color: rgb(167, 167, 167);")
        self.Btn_Dot.setObjectName("Btn_Dot")
        self.gridLayout_4.addWidget(self.Btn_Dot, 3, 7, 1, 1)
        self.pushButton_49 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_49.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_49.sizePolicy().hasHeightForWidth())
        self.pushButton_49.setSizePolicy(sizePolicy)
        self.pushButton_49.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_49.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_49.setStyleSheet("background-color: rgb(167, 167, 167);")
        self.pushButton_49.setText("")
        self.pushButton_49.setFlat(True)
        self.pushButton_49.setObjectName("pushButton_49")
        self.gridLayout_4.addWidget(self.pushButton_49, 3, 8, 1, 1)
        self.Btn_SHIFT = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_SHIFT.sizePolicy().hasHeightForWidth())
        self.Btn_SHIFT.setSizePolicy(sizePolicy)
        self.Btn_SHIFT.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_SHIFT.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Btn_SHIFT.setFont(font)
        self.Btn_SHIFT.setStyleSheet("background-color: rgb(160, 130, 90);\n"
"")
        self.Btn_SHIFT.setObjectName("Btn_SHIFT")
        self.gridLayout_4.addWidget(self.Btn_SHIFT, 4, 0, 1, 1)
        self.Btn_F = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_F.sizePolicy().hasHeightForWidth())
        self.Btn_F.setSizePolicy(sizePolicy)
        self.Btn_F.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_F.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_F.setStyleSheet("background-color: rgb(167, 167, 167);\n"
"image: url(:/framework/images/F_Btn.png);")
        self.Btn_F.setText("")
        self.Btn_F.setObjectName("Btn_F")
        self.gridLayout_4.addWidget(self.Btn_F, 4, 1, 1, 1)
        self.Btn_D = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_D.sizePolicy().hasHeightForWidth())
        self.Btn_D.setSizePolicy(sizePolicy)
        self.Btn_D.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_D.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_D.setStyleSheet("background-color: rgb(167, 167, 167);\n"
"image: url(:/framework/images/D_Btn.png);")
        self.Btn_D.setText("")
        self.Btn_D.setObjectName("Btn_D")
        self.gridLayout_4.addWidget(self.Btn_D, 4, 2, 1, 1)
        self.Btn_H = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_H.sizePolicy().hasHeightForWidth())
        self.Btn_H.setSizePolicy(sizePolicy)
        self.Btn_H.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_H.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_H.setStyleSheet("background-color: rgb(167, 167, 167);\n"
"image: url(:/framework/images/H_Btn.png);")
        self.Btn_H.setText("")
        self.Btn_H.setObjectName("Btn_H")
        self.gridLayout_4.addWidget(self.Btn_H, 4, 3, 1, 1)
        self.Btn_B = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_B.sizePolicy().hasHeightForWidth())
        self.Btn_B.setSizePolicy(sizePolicy)
        self.Btn_B.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_B.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_B.setStyleSheet("background-color: rgb(167, 167, 167);\n"
"image: url(:/framework/images/B_Btn.png);")
        self.Btn_B.setText("")
        self.Btn_B.setObjectName("Btn_B")
        self.gridLayout_4.addWidget(self.Btn_B, 4, 4, 1, 1)
        self.Btn_Slash = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_Slash.sizePolicy().hasHeightForWidth())
        self.Btn_Slash.setSizePolicy(sizePolicy)
        self.Btn_Slash.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_Slash.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Slash.setFont(font)
        self.Btn_Slash.setStyleSheet("background-color: rgb(167, 167, 167);")
        self.Btn_Slash.setObjectName("Btn_Slash")
        self.gridLayout_4.addWidget(self.Btn_Slash, 4, 5, 1, 1)
        self.Btn_EOB = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_EOB.sizePolicy().hasHeightForWidth())
        self.Btn_EOB.setSizePolicy(sizePolicy)
        self.Btn_EOB.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_EOB.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_EOB.setFont(font)
        self.Btn_EOB.setStyleSheet("background-color: rgb(167, 167, 167);")
        self.Btn_EOB.setObjectName("Btn_EOB")
        self.gridLayout_4.addWidget(self.Btn_EOB, 4, 6, 1, 1)
        self.Btn_CAN = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_CAN.sizePolicy().hasHeightForWidth())
        self.Btn_CAN.setSizePolicy(sizePolicy)
        self.Btn_CAN.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_CAN.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Btn_CAN.setFont(font)
        self.Btn_CAN.setStyleSheet("background-color: rgb(160, 130, 90);\n"
"")
        self.Btn_CAN.setObjectName("Btn_CAN")
        self.gridLayout_4.addWidget(self.Btn_CAN, 4, 7, 1, 1)
        self.Btn_INPUT = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_INPUT.sizePolicy().hasHeightForWidth())
        self.Btn_INPUT.setSizePolicy(sizePolicy)
        self.Btn_INPUT.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_INPUT.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Btn_INPUT.setFont(font)
        self.Btn_INPUT.setStyleSheet("background-color: rgb(160, 130, 90);\n"
"")
        self.Btn_INPUT.setObjectName("Btn_INPUT")
        self.gridLayout_4.addWidget(self.Btn_INPUT, 4, 8, 1, 1)
        self.Btn_HELP = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_HELP.sizePolicy().hasHeightForWidth())
        self.Btn_HELP.setSizePolicy(sizePolicy)
        self.Btn_HELP.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_HELP.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Btn_HELP.setFont(font)
        self.Btn_HELP.setStyleSheet("background-color: rgb(160, 130, 90);\n"
"")
        self.Btn_HELP.setObjectName("Btn_HELP")
        self.gridLayout_4.addWidget(self.Btn_HELP, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget_5, 0, 1, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.widget_2)
        self.widget_6.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_5.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_5.setSpacing(2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.Btn_DOWN = QtWidgets.QPushButton(self.widget_6)
        self.Btn_DOWN.setEnabled(False)
        self.Btn_DOWN.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_DOWN.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_DOWN.setStyleSheet("background-color: rgb(167, 167, 167);")
        self.Btn_DOWN.setText("")
        self.Btn_DOWN.setFlat(True)
        self.Btn_DOWN.setObjectName("Btn_DOWN")
        self.gridLayout_5.addWidget(self.Btn_DOWN, 0, 0, 1, 1)
        self.Btn_PAGE_UP = QtWidgets.QPushButton(self.widget_6)
        self.Btn_PAGE_UP.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_PAGE_UP.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_PAGE_UP.setFont(font)
        self.Btn_PAGE_UP.setStyleSheet("background-color: rgb(160, 130, 90);\n"
"")
        self.Btn_PAGE_UP.setObjectName("Btn_PAGE_UP")
        self.gridLayout_5.addWidget(self.Btn_PAGE_UP, 0, 1, 1, 1)
        self.Btn_LEFT = QtWidgets.QPushButton(self.widget_6)
        self.Btn_LEFT.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_LEFT.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_LEFT.setStyleSheet("background-color: rgb(160, 130, 90);\n"
"image: url(:/framework/images/left_btn1.png);\n"
"")
        self.Btn_LEFT.setText("")
        self.Btn_LEFT.setObjectName("Btn_LEFT")
        self.gridLayout_5.addWidget(self.Btn_LEFT, 0, 2, 2, 1)
        self.Btn_UP = QtWidgets.QPushButton(self.widget_6)
        self.Btn_UP.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_UP.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_UP.setStyleSheet("background-color: rgb(160, 130, 90);\n"
"image: url(:/framework/images/up_btn.png);\n"
"")
        self.Btn_UP.setText("")
        self.Btn_UP.setObjectName("Btn_UP")
        self.gridLayout_5.addWidget(self.Btn_UP, 0, 3, 1, 1)
        self.Btn_RIGHT = QtWidgets.QPushButton(self.widget_6)
        self.Btn_RIGHT.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_RIGHT.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_RIGHT.setStyleSheet("background-color: rgb(160, 130, 90);\n"
"image: url(:/framework/images/right_btn1.png);\n"
"")
        self.Btn_RIGHT.setText("")
        self.Btn_RIGHT.setObjectName("Btn_RIGHT")
        self.gridLayout_5.addWidget(self.Btn_RIGHT, 0, 4, 2, 1)
        self.Btn_POS = QtWidgets.QPushButton(self.widget_6)
        self.Btn_POS.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_POS.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Btn_POS.setFont(font)
        self.Btn_POS.setStyleSheet("background-color: rgb(160, 130, 90);\n"
"")
        self.Btn_POS.setObjectName("Btn_POS")
        self.gridLayout_5.addWidget(self.Btn_POS, 0, 5, 1, 1)
        self.Btn_PROG = QtWidgets.QPushButton(self.widget_6)
        self.Btn_PROG.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_PROG.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Btn_PROG.setFont(font)
        self.Btn_PROG.setStyleSheet("background-color: rgb(160, 130, 90);\n"
"")
        self.Btn_PROG.setObjectName("Btn_PROG")
        self.gridLayout_5.addWidget(self.Btn_PROG, 0, 6, 1, 1)
        self.Btn_SETTING = QtWidgets.QPushButton(self.widget_6)
        self.Btn_SETTING.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_SETTING.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_SETTING.setFont(font)
        self.Btn_SETTING.setStyleSheet("background-color: rgb(160, 130, 90);\n"
"")
        self.Btn_SETTING.setObjectName("Btn_SETTING")
        self.gridLayout_5.addWidget(self.Btn_SETTING, 0, 7, 1, 1)
        self.Btn_CUSTCM = QtWidgets.QPushButton(self.widget_6)
        self.Btn_CUSTCM.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_CUSTCM.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_CUSTCM.setFont(font)
        self.Btn_CUSTCM.setStyleSheet("background-color: rgb(160, 130, 90);\n"
"")
        self.Btn_CUSTCM.setObjectName("Btn_CUSTCM")
        self.gridLayout_5.addWidget(self.Btn_CUSTCM, 0, 8, 1, 1)
        self.pushButton_71 = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_71.setEnabled(False)
        self.pushButton_71.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_71.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_71.setStyleSheet("background-color: rgb(167, 167, 167);")
        self.pushButton_71.setText("")
        self.pushButton_71.setFlat(True)
        self.pushButton_71.setObjectName("pushButton_71")
        self.gridLayout_5.addWidget(self.pushButton_71, 1, 0, 1, 1)
        self.Btn_PAGE_DOWN = QtWidgets.QPushButton(self.widget_6)
        self.Btn_PAGE_DOWN.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_PAGE_DOWN.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Btn_PAGE_DOWN.setFont(font)
        self.Btn_PAGE_DOWN.setStyleSheet("background-color: rgb(160, 130, 90);\n"
"")
        self.Btn_PAGE_DOWN.setObjectName("Btn_PAGE_DOWN")
        self.gridLayout_5.addWidget(self.Btn_PAGE_DOWN, 1, 1, 1, 1)
        self.Btn_DOWN_2 = QtWidgets.QPushButton(self.widget_6)
        self.Btn_DOWN_2.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_DOWN_2.setMaximumSize(QtCore.QSize(40, 40))
        self.Btn_DOWN_2.setStyleSheet("background-color: rgb(160, 130, 90);\n"
"image: url(:/framework/images/down_btn.png);")
        self.Btn_DOWN_2.setText("")
        self.Btn_DOWN_2.setObjectName("Btn_DOWN_2")
        self.gridLayout_5.addWidget(self.Btn_DOWN_2, 1, 3, 1, 1)
        self.Btn_SYSTEM = QtWidgets.QPushButton(self.widget_6)
        self.Btn_SYSTEM.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_SYSTEM.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_SYSTEM.setFont(font)
        self.Btn_SYSTEM.setStyleSheet("background-color: rgb(160, 130, 90);\n"
"")
        self.Btn_SYSTEM.setObjectName("Btn_SYSTEM")
        self.gridLayout_5.addWidget(self.Btn_SYSTEM, 1, 5, 1, 1)
        self.Btn_MESSAGE = QtWidgets.QPushButton(self.widget_6)
        self.Btn_MESSAGE.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_MESSAGE.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_MESSAGE.setFont(font)
        self.Btn_MESSAGE.setStyleSheet("background-color: rgb(160, 130, 90);\n"
"")
        self.Btn_MESSAGE.setObjectName("Btn_MESSAGE")
        self.gridLayout_5.addWidget(self.Btn_MESSAGE, 1, 6, 1, 1)
        self.Btn_GRAPH = QtWidgets.QPushButton(self.widget_6)
        self.Btn_GRAPH.setMinimumSize(QtCore.QSize(40, 40))
        self.Btn_GRAPH.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Btn_GRAPH.setFont(font)
        self.Btn_GRAPH.setStyleSheet("background-color: rgb(160, 130, 90);\n"
"")
        self.Btn_GRAPH.setObjectName("Btn_GRAPH")
        self.gridLayout_5.addWidget(self.Btn_GRAPH, 1, 7, 1, 1)
        self.pushButton_67 = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_67.setEnabled(False)
        self.pushButton_67.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_67.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_67.setStyleSheet("background-color: rgb(160, 130, 90);\n"
"")
        self.pushButton_67.setText("")
        self.pushButton_67.setFlat(True)
        self.pushButton_67.setObjectName("pushButton_67")
        self.gridLayout_5.addWidget(self.pushButton_67, 1, 8, 1, 1)
        self.gridLayout_2.addWidget(self.widget_6, 1, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 2)
        self.gridLayout_2.setColumnStretch(1, 9)
        self.gridLayout_2.setColumnStretch(2, 3)
        self.gridLayout_2.setRowStretch(0, 5)
        self.gridLayout_2.setRowStretch(1, 2)
        self.gridLayout.addWidget(self.widget_2, 2, 0, 1, 1)
        self.main_window = QtWidgets.QWidget(Form)
        self.main_window.setStyleSheet("background-color: rgb(64, 64, 64);")
        self.main_window.setObjectName("main_window")
        self.gridLayout.addWidget(self.main_window, 0, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_3.setContentsMargins(2, 0, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(1)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_9 = QtWidgets.QWidget(self.widget_3)
        self.widget_9.setStyleSheet("background-color: rgb(127, 255, 107);")
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout.setContentsMargins(3, 0, 0, 0)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dial_5 = QtWidgets.QDial(self.widget_9)
        self.dial_5.setMinimumSize(QtCore.QSize(145, 145))
        self.dial_5.setMaximumSize(QtCore.QSize(145, 145))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.dial_5.setFont(font)
        self.dial_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dial_5.setNotchesVisible(False)
        self.dial_5.setObjectName("dial_5")
        self.verticalLayout.addWidget(self.dial_5)
        self.dial_4 = QtWidgets.QDial(self.widget_9)
        self.dial_4.setMinimumSize(QtCore.QSize(145, 145))
        self.dial_4.setMaximumSize(QtCore.QSize(145, 145))
        self.dial_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dial_4.setMinimum(50)
        self.dial_4.setMaximum(120)
        self.dial_4.setSingleStep(10)
        self.dial_4.setInvertedAppearance(False)
        self.dial_4.setInvertedControls(False)
        self.dial_4.setWrapping(False)
        self.dial_4.setNotchTarget(10.0)
        self.dial_4.setNotchesVisible(True)
        self.dial_4.setObjectName("dial_4")
        self.verticalLayout.addWidget(self.dial_4)
        self.dial_3 = QtWidgets.QDial(self.widget_9)
        self.dial_3.setMinimumSize(QtCore.QSize(145, 145))
        self.dial_3.setMaximumSize(QtCore.QSize(145, 145))
        self.dial_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dial_3.setObjectName("dial_3")
        self.verticalLayout.addWidget(self.dial_3)
        self.Btn_Emergency_STOP = QtWidgets.QPushButton(self.widget_9)
        self.Btn_Emergency_STOP.setMinimumSize(QtCore.QSize(145, 145))
        self.Btn_Emergency_STOP.setMaximumSize(QtCore.QSize(145, 145))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.Btn_Emergency_STOP.setFont(font)
        self.Btn_Emergency_STOP.setStyleSheet("QPushButton#Btn_Emergency_STOP {\n"
"    background-color: rgb(217, 0, 0);\n"
"    image: url(:/framework/images/Emergency_STOP_Close.png);\n"
"}\n"
"QPushButton#Btn_Emergency_STOP:checked {\n"
"    background-color: rgb(217, 0, 0);\n"
"    image: url(:/framework/images/Emergency_STOP_Open.png);\n"
"}")
        self.Btn_Emergency_STOP.setText("")
        self.Btn_Emergency_STOP.setCheckable(True)
        self.Btn_Emergency_STOP.setObjectName("Btn_Emergency_STOP")
        self.verticalLayout.addWidget(self.Btn_Emergency_STOP)
        self.gridLayout_3.addWidget(self.widget_9, 0, 0, 2, 1)
        self.widget_11 = QtWidgets.QWidget(self.widget_3)
        self.widget_11.setStyleSheet("background-color: rgb(127, 255, 107);")
        self.widget_11.setObjectName("widget_11")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_11)
        self.gridLayout_6.setContentsMargins(0, 2, 0, 2)
        self.gridLayout_6.setSpacing(2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label = QtWidgets.QLabel(self.widget_11)
        self.label.setMinimumSize(QtCore.QSize(50, 25))
        self.label.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(32, 32, 32);\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_11)
        self.label_2.setMinimumSize(QtCore.QSize(50, 25))
        self.label_2.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(32, 32, 32);\n"
"color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_11)
        self.label_3.setMinimumSize(QtCore.QSize(50, 25))
        self.label_3.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(32, 32, 32);\n"
"color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 0, 2, 1, 1)
        self.Btn_A_Positive = QtWidgets.QPushButton(self.widget_11)
        self.Btn_A_Positive.setMinimumSize(QtCore.QSize(50, 35))
        self.Btn_A_Positive.setMaximumSize(QtCore.QSize(50, 35))
        self.Btn_A_Positive.setStyleSheet("background-color: rgb(26, 181, 152);")
        self.Btn_A_Positive.setText("")
        self.Btn_A_Positive.setCheckable(False)
        self.Btn_A_Positive.setObjectName("Btn_A_Positive")
        self.gridLayout_6.addWidget(self.Btn_A_Positive, 1, 0, 1, 1)
        self.Btn_Z_Positive = QtWidgets.QPushButton(self.widget_11)
        self.Btn_Z_Positive.setMinimumSize(QtCore.QSize(50, 35))
        self.Btn_Z_Positive.setMaximumSize(QtCore.QSize(50, 35))
        self.Btn_Z_Positive.setStyleSheet("background-color: rgb(26, 181, 152);")
        self.Btn_Z_Positive.setText("")
        self.Btn_Z_Positive.setCheckable(False)
        self.Btn_Z_Positive.setObjectName("Btn_Z_Positive")
        self.gridLayout_6.addWidget(self.Btn_Z_Positive, 1, 1, 1, 1)
        self.Btn_Y_Negative = QtWidgets.QPushButton(self.widget_11)
        self.Btn_Y_Negative.setMinimumSize(QtCore.QSize(50, 35))
        self.Btn_Y_Negative.setMaximumSize(QtCore.QSize(50, 35))
        self.Btn_Y_Negative.setStyleSheet("background-color: rgb(26, 181, 152);")
        self.Btn_Y_Negative.setText("")
        self.Btn_Y_Negative.setCheckable(False)
        self.Btn_Y_Negative.setObjectName("Btn_Y_Negative")
        self.gridLayout_6.addWidget(self.Btn_Y_Negative, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_11)
        self.label_6.setMinimumSize(QtCore.QSize(50, 25))
        self.label_6.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(32, 32, 32);\n"
"color: rgb(255, 255, 255);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_11)
        self.label_5.setMinimumSize(QtCore.QSize(50, 25))
        self.label_5.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(32, 32, 32);\n"
"color: rgb(255, 255, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_11)
        self.label_4.setMinimumSize(QtCore.QSize(50, 25))
        self.label_4.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(32, 32, 32);\n"
"color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 2, 2, 1, 1)
        self.Btn_X_Positive = QtWidgets.QPushButton(self.widget_11)
        self.Btn_X_Positive.setMinimumSize(QtCore.QSize(50, 35))
        self.Btn_X_Positive.setMaximumSize(QtCore.QSize(50, 35))
        self.Btn_X_Positive.setStyleSheet("background-color: rgb(26, 181, 152);")
        self.Btn_X_Positive.setText("")
        self.Btn_X_Positive.setCheckable(False)
        self.Btn_X_Positive.setObjectName("Btn_X_Positive")
        self.gridLayout_6.addWidget(self.Btn_X_Positive, 3, 0, 1, 1)
        self.Btn_RAPID = QtWidgets.QPushButton(self.widget_11)
        self.Btn_RAPID.setMinimumSize(QtCore.QSize(50, 35))
        self.Btn_RAPID.setMaximumSize(QtCore.QSize(50, 35))
        self.Btn_RAPID.setStyleSheet("background-color: rgb(26, 181, 152);")
        self.Btn_RAPID.setText("")
        self.Btn_RAPID.setCheckable(False)
        self.Btn_RAPID.setObjectName("Btn_RAPID")
        self.gridLayout_6.addWidget(self.Btn_RAPID, 3, 1, 1, 1)
        self.Btn_X_Negative = QtWidgets.QPushButton(self.widget_11)
        self.Btn_X_Negative.setMinimumSize(QtCore.QSize(50, 35))
        self.Btn_X_Negative.setMaximumSize(QtCore.QSize(50, 35))
        self.Btn_X_Negative.setStyleSheet("background-color: rgb(26, 181, 152);")
        self.Btn_X_Negative.setText("")
        self.Btn_X_Negative.setCheckable(False)
        self.Btn_X_Negative.setObjectName("Btn_X_Negative")
        self.gridLayout_6.addWidget(self.Btn_X_Negative, 3, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget_11)
        self.label_9.setMinimumSize(QtCore.QSize(50, 25))
        self.label_9.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(32, 32, 32);\n"
"color: rgb(255, 255, 255);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget_11)
        self.label_8.setMinimumSize(QtCore.QSize(50, 25))
        self.label_8.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(32, 32, 32);\n"
"color: rgb(255, 255, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_11)
        self.label_7.setMinimumSize(QtCore.QSize(50, 25))
        self.label_7.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(32, 32, 32);\n"
"color: rgb(255, 255, 255);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 4, 2, 1, 1)
        self.Btn_Y_Positive = QtWidgets.QPushButton(self.widget_11)
        self.Btn_Y_Positive.setMinimumSize(QtCore.QSize(50, 35))
        self.Btn_Y_Positive.setMaximumSize(QtCore.QSize(50, 35))
        self.Btn_Y_Positive.setStyleSheet("background-color: rgb(26, 181, 152);")
        self.Btn_Y_Positive.setText("")
        self.Btn_Y_Positive.setCheckable(False)
        self.Btn_Y_Positive.setObjectName("Btn_Y_Positive")
        self.gridLayout_6.addWidget(self.Btn_Y_Positive, 5, 0, 1, 1)
        self.Btn_Z_Negative = QtWidgets.QPushButton(self.widget_11)
        self.Btn_Z_Negative.setMinimumSize(QtCore.QSize(50, 35))
        self.Btn_Z_Negative.setMaximumSize(QtCore.QSize(50, 35))
        self.Btn_Z_Negative.setStyleSheet("background-color: rgb(26, 181, 152);")
        self.Btn_Z_Negative.setText("")
        self.Btn_Z_Negative.setCheckable(False)
        self.Btn_Z_Negative.setObjectName("Btn_Z_Negative")
        self.gridLayout_6.addWidget(self.Btn_Z_Negative, 5, 1, 1, 1)
        self.Btn_A_Negative = QtWidgets.QPushButton(self.widget_11)
        self.Btn_A_Negative.setMinimumSize(QtCore.QSize(50, 35))
        self.Btn_A_Negative.setMaximumSize(QtCore.QSize(50, 35))
        self.Btn_A_Negative.setStyleSheet("background-color: rgb(26, 181, 152);")
        self.Btn_A_Negative.setText("")
        self.Btn_A_Negative.setCheckable(False)
        self.Btn_A_Negative.setObjectName("Btn_A_Negative")
        self.gridLayout_6.addWidget(self.Btn_A_Negative, 5, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget_11)
        self.label_12.setMinimumSize(QtCore.QSize(50, 25))
        self.label_12.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: rgb(32, 32, 32);\n"
"color: rgb(255, 255, 255);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 6, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget_11)
        self.label_11.setMinimumSize(QtCore.QSize(50, 25))
        self.label_11.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: rgb(32, 32, 32);\n"
"color: rgb(255, 255, 255);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 6, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget_11)
        self.label_10.setMinimumSize(QtCore.QSize(50, 25))
        self.label_10.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(32, 32, 32);\n"
"color: rgb(255, 255, 255);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 6, 2, 1, 1)
        self.Btn_ON = QtWidgets.QPushButton(self.widget_11)
        self.Btn_ON.setMinimumSize(QtCore.QSize(50, 35))
        self.Btn_ON.setMaximumSize(QtCore.QSize(50, 35))
        self.Btn_ON.setStyleSheet("background-color: rgb(26, 181, 152);")
        self.Btn_ON.setText("")
        self.Btn_ON.setCheckable(False)
        self.Btn_ON.setObjectName("Btn_ON")
        self.gridLayout_6.addWidget(self.Btn_ON, 7, 0, 1, 1)
        self.Btn_STOP = QtWidgets.QPushButton(self.widget_11)
        self.Btn_STOP.setMinimumSize(QtCore.QSize(50, 35))
        self.Btn_STOP.setMaximumSize(QtCore.QSize(50, 35))
        self.Btn_STOP.setStyleSheet("background-color: rgb(217, 0, 0);")
        self.Btn_STOP.setText("")
        self.Btn_STOP.setCheckable(False)
        self.Btn_STOP.setObjectName("Btn_STOP")
        self.gridLayout_6.addWidget(self.Btn_STOP, 7, 1, 1, 1)
        self.Btn_COW = QtWidgets.QPushButton(self.widget_11)
        self.Btn_COW.setMinimumSize(QtCore.QSize(50, 35))
        self.Btn_COW.setMaximumSize(QtCore.QSize(50, 35))
        self.Btn_COW.setStyleSheet("background-color: rgb(26, 181, 152);")
        self.Btn_COW.setText("")
        self.Btn_COW.setCheckable(False)
        self.Btn_COW.setObjectName("Btn_COW")
        self.gridLayout_6.addWidget(self.Btn_COW, 7, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget_11)
        self.label_15.setMinimumSize(QtCore.QSize(50, 25))
        self.label_15.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("background-color: rgb(32, 32, 32);\n"
"color: rgb(255, 255, 255);")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 8, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget_11)
        self.label_14.setMinimumSize(QtCore.QSize(50, 25))
        self.label_14.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: rgb(32, 32, 32);\n"
"color: rgb(255, 255, 255);")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 8, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget_11)
        self.label_13.setMinimumSize(QtCore.QSize(50, 25))
        self.label_13.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color: rgb(32, 32, 32);\n"
"color: rgb(255, 255, 255);")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 8, 2, 1, 1)
        self.Btn_DRN = QtWidgets.QPushButton(self.widget_11)
        self.Btn_DRN.setMinimumSize(QtCore.QSize(50, 35))
        self.Btn_DRN.setMaximumSize(QtCore.QSize(50, 35))
        self.Btn_DRN.setStyleSheet("background-color: rgb(26, 181, 152);")
        self.Btn_DRN.setText("")
        self.Btn_DRN.setCheckable(False)
        self.Btn_DRN.setObjectName("Btn_DRN")
        self.gridLayout_6.addWidget(self.Btn_DRN, 9, 0, 1, 1)
        self.Btn_SRN = QtWidgets.QPushButton(self.widget_11)
        self.Btn_SRN.setMinimumSize(QtCore.QSize(50, 35))
        self.Btn_SRN.setMaximumSize(QtCore.QSize(50, 35))
        self.Btn_SRN.setStyleSheet("background-color: rgb(26, 181, 152);")
        self.Btn_SRN.setText("")
        self.Btn_SRN.setCheckable(False)
        self.Btn_SRN.setObjectName("Btn_SRN")
        self.gridLayout_6.addWidget(self.Btn_SRN, 9, 1, 1, 1)
        self.Btn_TOOL = QtWidgets.QPushButton(self.widget_11)
        self.Btn_TOOL.setMinimumSize(QtCore.QSize(50, 35))
        self.Btn_TOOL.setMaximumSize(QtCore.QSize(50, 35))
        self.Btn_TOOL.setStyleSheet("background-color: rgb(26, 181, 152);")
        self.Btn_TOOL.setText("")
        self.Btn_TOOL.setCheckable(False)
        self.Btn_TOOL.setObjectName("Btn_TOOL")
        self.gridLayout_6.addWidget(self.Btn_TOOL, 9, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.widget_11)
        self.label_18.setMinimumSize(QtCore.QSize(50, 25))
        self.label_18.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background-color: rgb(32, 32, 32);\n"
"color: rgb(255, 255, 255);")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 10, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.widget_11)
        self.label_17.setMinimumSize(QtCore.QSize(50, 25))
        self.label_17.setMaximumSize(QtCore.QSize(50, 25))
        self.label_17.setStyleSheet("background-color: rgb(32, 32, 32);\n"
"color: rgb(255, 255, 255);")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_6.addWidget(self.label_17, 10, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.widget_11)
        self.label_16.setMinimumSize(QtCore.QSize(50, 25))
        self.label_16.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color: rgb(32, 32, 32);\n"
"color: rgb(255, 255, 255);")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 10, 2, 1, 1)
        self.Btn_DNC = QtWidgets.QPushButton(self.widget_11)
        self.Btn_DNC.setMinimumSize(QtCore.QSize(50, 35))
        self.Btn_DNC.setMaximumSize(QtCore.QSize(50, 35))
        self.Btn_DNC.setStyleSheet("background-color: rgb(26, 181, 152);")
        self.Btn_DNC.setText("")
        self.Btn_DNC.setCheckable(False)
        self.Btn_DNC.setObjectName("Btn_DNC")
        self.gridLayout_6.addWidget(self.Btn_DNC, 11, 0, 1, 1)
        self.Btn_MSTLOCK = QtWidgets.QPushButton(self.widget_11)
        self.Btn_MSTLOCK.setMinimumSize(QtCore.QSize(50, 35))
        self.Btn_MSTLOCK.setMaximumSize(QtCore.QSize(50, 35))
        self.Btn_MSTLOCK.setStyleSheet("background-color: rgb(26, 181, 152);")
        self.Btn_MSTLOCK.setText("")
        self.Btn_MSTLOCK.setCheckable(False)
        self.Btn_MSTLOCK.setObjectName("Btn_MSTLOCK")
        self.gridLayout_6.addWidget(self.Btn_MSTLOCK, 11, 1, 1, 1)
        self.Btn_COOL = QtWidgets.QPushButton(self.widget_11)
        self.Btn_COOL.setMinimumSize(QtCore.QSize(50, 35))
        self.Btn_COOL.setMaximumSize(QtCore.QSize(50, 35))
        self.Btn_COOL.setStyleSheet("background-color: rgb(26, 181, 152);")
        self.Btn_COOL.setText("")
        self.Btn_COOL.setCheckable(False)
        self.Btn_COOL.setObjectName("Btn_COOL")
        self.gridLayout_6.addWidget(self.Btn_COOL, 11, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.widget_11)
        self.label_21.setMinimumSize(QtCore.QSize(50, 25))
        self.label_21.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("background-color: rgb(32, 32, 32);\n"
"color: rgb(255, 255, 255);")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_6.addWidget(self.label_21, 12, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.widget_11)
        self.label_20.setMinimumSize(QtCore.QSize(50, 25))
        self.label_20.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background-color: rgb(32, 32, 32);\n"
"color: rgb(255, 255, 255);")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 12, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.widget_11)
        self.label_19.setMinimumSize(QtCore.QSize(50, 25))
        self.label_19.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background-color: rgb(32, 32, 32);\n"
"color: rgb(255, 255, 255);")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 12, 2, 1, 1)
        self.Btn_SBK = QtWidgets.QPushButton(self.widget_11)
        self.Btn_SBK.setMinimumSize(QtCore.QSize(50, 35))
        self.Btn_SBK.setMaximumSize(QtCore.QSize(50, 35))
        self.Btn_SBK.setStyleSheet("background-color: rgb(26, 181, 152);")
        self.Btn_SBK.setText("")
        self.Btn_SBK.setCheckable(False)
        self.Btn_SBK.setObjectName("Btn_SBK")
        self.gridLayout_6.addWidget(self.Btn_SBK, 13, 0, 1, 1)
        self.Btn_SKIP = QtWidgets.QPushButton(self.widget_11)
        self.Btn_SKIP.setMinimumSize(QtCore.QSize(50, 35))
        self.Btn_SKIP.setMaximumSize(QtCore.QSize(50, 35))
        self.Btn_SKIP.setStyleSheet("background-color: rgb(26, 181, 152);")
        self.Btn_SKIP.setText("")
        self.Btn_SKIP.setCheckable(False)
        self.Btn_SKIP.setObjectName("Btn_SKIP")
        self.gridLayout_6.addWidget(self.Btn_SKIP, 13, 1, 1, 1)
        self.Btn_DRIVE = QtWidgets.QPushButton(self.widget_11)
        self.Btn_DRIVE.setMinimumSize(QtCore.QSize(50, 35))
        self.Btn_DRIVE.setMaximumSize(QtCore.QSize(50, 35))
        self.Btn_DRIVE.setStyleSheet("QPushButton#Btn_DRIVE {\n"
"    background-color: rgb(26, 181, 152);\n"
"    image: url(:/framework/images/DRIVE_Close.png);\n"
"}\n"
"QPushButton#Btn_DRIVE:checked {\n"
"    background-color: rgb(26, 181, 152);\n"
"    image: url(:/framework/images/DRIVE_Open.png);\n"
"}\n"
"")
        self.Btn_DRIVE.setText("")
        self.Btn_DRIVE.setCheckable(True)
        self.Btn_DRIVE.setObjectName("Btn_DRIVE")
        self.gridLayout_6.addWidget(self.Btn_DRIVE, 13, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.widget_11)
        self.label_24.setMinimumSize(QtCore.QSize(50, 25))
        self.label_24.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("background-color: rgb(32, 32, 32);\n"
"color: rgb(255, 255, 255);")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_6.addWidget(self.label_24, 14, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.widget_11)
        self.label_23.setMinimumSize(QtCore.QSize(50, 25))
        self.label_23.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("background-color: rgb(32, 32, 32);\n"
"color: rgb(255, 255, 255);")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_6.addWidget(self.label_23, 14, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.widget_11)
        self.label_22.setMinimumSize(QtCore.QSize(50, 25))
        self.label_22.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("background-color: rgb(32, 32, 32);\n"
"color: rgb(255, 255, 255);")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_6.addWidget(self.label_22, 14, 2, 1, 1)
        self.Btn_MPG = QtWidgets.QPushButton(self.widget_11)
        self.Btn_MPG.setMinimumSize(QtCore.QSize(50, 35))
        self.Btn_MPG.setMaximumSize(QtCore.QSize(50, 35))
        self.Btn_MPG.setStyleSheet("background-color: rgb(26, 181, 152);")
        self.Btn_MPG.setText("")
        self.Btn_MPG.setCheckable(False)
        self.Btn_MPG.setObjectName("Btn_MPG")
        self.gridLayout_6.addWidget(self.Btn_MPG, 15, 0, 1, 1)
        self.Btn_M01 = QtWidgets.QPushButton(self.widget_11)
        self.Btn_M01.setMinimumSize(QtCore.QSize(50, 35))
        self.Btn_M01.setMaximumSize(QtCore.QSize(50, 35))
        self.Btn_M01.setStyleSheet("background-color: rgb(26, 181, 152);")
        self.Btn_M01.setText("")
        self.Btn_M01.setCheckable(False)
        self.Btn_M01.setObjectName("Btn_M01")
        self.gridLayout_6.addWidget(self.Btn_M01, 15, 1, 1, 1)
        self.Btn_PROTECT = QtWidgets.QPushButton(self.widget_11)
        self.Btn_PROTECT.setMinimumSize(QtCore.QSize(50, 35))
        self.Btn_PROTECT.setMaximumSize(QtCore.QSize(50, 35))
        self.Btn_PROTECT.setStyleSheet("QPushButton#Btn_PROTECT {\n"
"    background-color: rgb(26, 181, 152);\n"
"    image: url(:/framework/images/DRIVE_Close.png);\n"
"}\n"
"QPushButton#Btn_PROTECT:checked {\n"
"    background-color: rgb(26, 181, 152);\n"
"    image: url(:/framework/images/DRIVE_Open.png);\n"
"}\n"
"")
        self.Btn_PROTECT.setText("")
        self.Btn_PROTECT.setCheckable(True)
        self.Btn_PROTECT.setObjectName("Btn_PROTECT")
        self.gridLayout_6.addWidget(self.Btn_PROTECT, 15, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.widget_11)
        self.label_27.setMinimumSize(QtCore.QSize(50, 25))
        self.label_27.setMaximumSize(QtCore.QSize(50, 25))
        self.label_27.setStyleSheet("image: url(:/framework/images/Diamond_icon.png);\n"
"color: rgb(255, 255, 255);")
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.gridLayout_6.addWidget(self.label_27, 16, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.widget_11)
        self.label_26.setMinimumSize(QtCore.QSize(50, 25))
        self.label_26.setMaximumSize(QtCore.QSize(50, 25))
        self.label_26.setStyleSheet("image: url(:/framework/images/Triangle_icon.png);\n"
"color: rgb(255, 255, 255);")
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.gridLayout_6.addWidget(self.label_26, 16, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.widget_11)
        self.label_25.setMinimumSize(QtCore.QSize(50, 25))
        self.label_25.setMaximumSize(QtCore.QSize(50, 25))
        self.label_25.setStyleSheet("image: url(:/framework/images/Slash_icon.png);\n"
"color: rgb(255, 255, 255);")
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.gridLayout_6.addWidget(self.label_25, 16, 2, 1, 1)
        self.pushButton_100 = QtWidgets.QPushButton(self.widget_11)
        self.pushButton_100.setMinimumSize(QtCore.QSize(50, 35))
        self.pushButton_100.setMaximumSize(QtCore.QSize(50, 35))
        self.pushButton_100.setStyleSheet("background-color: rgb(26, 181, 152);")
        self.pushButton_100.setText("")
        self.pushButton_100.setCheckable(False)
        self.pushButton_100.setObjectName("pushButton_100")
        self.gridLayout_6.addWidget(self.pushButton_100, 17, 0, 1, 1)
        self.pushButton_98 = QtWidgets.QPushButton(self.widget_11)
        self.pushButton_98.setMinimumSize(QtCore.QSize(50, 35))
        self.pushButton_98.setMaximumSize(QtCore.QSize(50, 35))
        self.pushButton_98.setStyleSheet("background-color: rgb(217, 0, 0);")
        self.pushButton_98.setText("")
        self.pushButton_98.setCheckable(False)
        self.pushButton_98.setObjectName("pushButton_98")
        self.gridLayout_6.addWidget(self.pushButton_98, 17, 1, 1, 1)
        self.pushButton_99 = QtWidgets.QPushButton(self.widget_11)
        self.pushButton_99.setMinimumSize(QtCore.QSize(50, 35))
        self.pushButton_99.setMaximumSize(QtCore.QSize(50, 35))
        self.pushButton_99.setStyleSheet("background-color: rgb(217, 0, 0);")
        self.pushButton_99.setText("")
        self.pushButton_99.setCheckable(False)
        self.pushButton_99.setObjectName("pushButton_99")
        self.gridLayout_6.addWidget(self.pushButton_99, 17, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.widget_11)
        self.label_30.setMinimumSize(QtCore.QSize(50, 25))
        self.label_30.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("background-color: rgb(32, 32, 32);\n"
"color: rgb(255, 255, 255);")
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_6.addWidget(self.label_30, 18, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.widget_11)
        self.label_29.setMinimumSize(QtCore.QSize(50, 25))
        self.label_29.setMaximumSize(QtCore.QSize(50, 25))
        self.label_29.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_29.setText("")
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_6.addWidget(self.label_29, 18, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.widget_11)
        self.label_28.setMinimumSize(QtCore.QSize(50, 25))
        self.label_28.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("background-color: rgb(32, 32, 32);\n"
"color: rgb(255, 255, 255);")
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_6.addWidget(self.label_28, 18, 2, 1, 1)
        self.Btn_Power_OFF = QtWidgets.QPushButton(self.widget_11)
        self.Btn_Power_OFF.setMinimumSize(QtCore.QSize(50, 35))
        self.Btn_Power_OFF.setMaximumSize(QtCore.QSize(50, 35))
        self.Btn_Power_OFF.setStyleSheet("background-color: rgb(217, 0, 0);")
        self.Btn_Power_OFF.setText("")
        self.Btn_Power_OFF.setCheckable(False)
        self.Btn_Power_OFF.setObjectName("Btn_Power_OFF")
        self.gridLayout_6.addWidget(self.Btn_Power_OFF, 19, 0, 1, 1)
        self.pushButton_101 = QtWidgets.QPushButton(self.widget_11)
        self.pushButton_101.setEnabled(False)
        self.pushButton_101.setMinimumSize(QtCore.QSize(50, 35))
        self.pushButton_101.setMaximumSize(QtCore.QSize(50, 35))
        self.pushButton_101.setStyleSheet("background-color: rgb(26, 181, 152);")
        self.pushButton_101.setText("")
        self.pushButton_101.setCheckable(False)
        self.pushButton_101.setFlat(True)
        self.pushButton_101.setObjectName("pushButton_101")
        self.gridLayout_6.addWidget(self.pushButton_101, 19, 1, 1, 1)
        self.Btn_Power_ON = QtWidgets.QPushButton(self.widget_11)
        self.Btn_Power_ON.setMinimumSize(QtCore.QSize(50, 35))
        self.Btn_Power_ON.setMaximumSize(QtCore.QSize(50, 35))
        self.Btn_Power_ON.setStyleSheet("background-color: rgb(26, 181, 152);")
        self.Btn_Power_ON.setText("")
        self.Btn_Power_ON.setCheckable(False)
        self.Btn_Power_ON.setObjectName("Btn_Power_ON")
        self.gridLayout_6.addWidget(self.Btn_Power_ON, 19, 2, 1, 1)
        self.gridLayout_3.addWidget(self.widget_11, 0, 1, 1, 1)
        self.widget_10 = QtWidgets.QWidget(self.widget_3)
        self.widget_10.setStyleSheet("background-color: rgb(40, 40, 40);")
        self.widget_10.setObjectName("widget_10")
        self.gridLayout_3.addWidget(self.widget_10, 1, 1, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 7)
        self.gridLayout_3.setColumnStretch(1, 9)
        self.gridLayout_3.setRowStretch(0, 15)
        self.gridLayout_3.setRowStretch(1, 3)
        self.gridLayout.addWidget(self.widget_3, 0, 1, 3, 1)
        self.widget_4 = QtWidgets.QWidget(Form)
        self.widget_4.setStyleSheet("background-color: rgb(115, 115, 115);")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout.setContentsMargins(2, -1, 2, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Btn_BACK = QtWidgets.QPushButton(self.widget_4)
        self.Btn_BACK.setMinimumSize(QtCore.QSize(40, 20))
        self.Btn_BACK.setMaximumSize(QtCore.QSize(40, 20))
        self.Btn_BACK.setStyleSheet("QPushButton {\n"
"    background-color: rgb(222, 222, 222);\n"
"    image: url(:/framework/images/left_btn.png);\n"
"}")
        self.Btn_BACK.setText("")
        self.Btn_BACK.setIconSize(QtCore.QSize(40, 20))
        self.Btn_BACK.setFlat(False)
        self.Btn_BACK.setObjectName("Btn_BACK")
        self.horizontalLayout.addWidget(self.Btn_BACK)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_2.setMinimumSize(QtCore.QSize(40, 20))
        self.pushButton_2.setMaximumSize(QtCore.QSize(40, 20))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(222, 222, 222);\n"
"}")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_3.setMinimumSize(QtCore.QSize(40, 20))
        self.pushButton_3.setMaximumSize(QtCore.QSize(40, 20))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: rgb(222, 222, 222);\n"
"}")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_4.setMinimumSize(QtCore.QSize(40, 20))
        self.pushButton_4.setMaximumSize(QtCore.QSize(40, 20))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: rgb(222, 222, 222);\n"
"}")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_5.setMinimumSize(QtCore.QSize(40, 20))
        self.pushButton_5.setMaximumSize(QtCore.QSize(40, 20))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: rgb(222, 222, 222);\n"
"}")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_6.setMinimumSize(QtCore.QSize(40, 20))
        self.pushButton_6.setMaximumSize(QtCore.QSize(40, 20))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: rgb(222, 222, 222);\n"
"}")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_7.setMinimumSize(QtCore.QSize(40, 20))
        self.pushButton_7.setMaximumSize(QtCore.QSize(40, 20))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background-color: rgb(222, 222, 222);\n"
"}")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_8.setMinimumSize(QtCore.QSize(40, 20))
        self.pushButton_8.setMaximumSize(QtCore.QSize(40, 20))
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background-color: rgb(222, 222, 222);\n"
"}")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_9.setMinimumSize(QtCore.QSize(40, 20))
        self.pushButton_9.setMaximumSize(QtCore.QSize(40, 20))
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    background-color: rgb(222, 222, 222);\n"
"}")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_10.setMinimumSize(QtCore.QSize(40, 20))
        self.pushButton_10.setMaximumSize(QtCore.QSize(40, 20))
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    background-color: rgb(222, 222, 222);\n"
"}")
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_11.setMinimumSize(QtCore.QSize(40, 20))
        self.pushButton_11.setMaximumSize(QtCore.QSize(40, 20))
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"    background-color: rgb(222, 222, 222);\n"
"}")
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout.addWidget(self.pushButton_11)
        self.Btn_GO = QtWidgets.QPushButton(self.widget_4)
        self.Btn_GO.setMinimumSize(QtCore.QSize(40, 20))
        self.Btn_GO.setMaximumSize(QtCore.QSize(40, 20))
        self.Btn_GO.setStyleSheet("QPushButton {\n"
"    background-color: rgb(222, 222, 222);\n"
"    image: url(:/framework/images/right_btn.png);\n"
"}")
        self.Btn_GO.setObjectName("Btn_GO")
        self.horizontalLayout.addWidget(self.Btn_GO)
        self.gridLayout.addWidget(self.widget_4, 1, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setRowStretch(0, 10)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(2, 8)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "FANUC Series 18i MB"))
        self.Btn_RESET.setText(_translate("Form", "RESET"))
        self.Btn_ALTER.setText(_translate("Form", "ALTER"))
        self.Btn_INSERT.setText(_translate("Form", "INSERT"))
        self.Btn_DELETE.setText(_translate("Form", "DELETE"))
        self.Btn_Minus.setText(_translate("Form", "-"))
        self.Btn_0.setText(_translate("Form", "0"))
        self.Btn_Dot.setText(_translate("Form", "."))
        self.Btn_SHIFT.setText(_translate("Form", "SHIFT"))
        self.Btn_Slash.setText(_translate("Form", "/"))
        self.Btn_EOB.setText(_translate("Form", "EOB"))
        self.Btn_CAN.setText(_translate("Form", "CAN"))
        self.Btn_INPUT.setText(_translate("Form", "INPUT"))
        self.Btn_HELP.setText(_translate("Form", "HELP"))
        self.Btn_PAGE_UP.setText(_translate("Form", "UP"))
        self.Btn_POS.setText(_translate("Form", "POS"))
        self.Btn_PROG.setText(_translate("Form", "PROG"))
        self.Btn_SETTING.setText(_translate("Form", "SETTING"))
        self.Btn_CUSTCM.setText(_translate("Form", "CUSTCM"))
        self.Btn_PAGE_DOWN.setText(_translate("Form", "DOWN"))
        self.Btn_SYSTEM.setText(_translate("Form", "SYSTEM"))
        self.Btn_MESSAGE.setText(_translate("Form", "MESSAGE"))
        self.Btn_GRAPH.setText(_translate("Form", "GRAPH"))
        self.label.setText(_translate("Form", "A+"))
        self.label_2.setText(_translate("Form", "Z+"))
        self.label_3.setText(_translate("Form", "Y-"))
        self.label_6.setText(_translate("Form", "X+"))
        self.label_5.setText(_translate("Form", "RAPID"))
        self.label_4.setText(_translate("Form", "X-"))
        self.label_9.setText(_translate("Form", "Y+"))
        self.label_8.setText(_translate("Form", "Z-"))
        self.label_7.setText(_translate("Form", "A-"))
        self.label_12.setText(_translate("Form", "ON"))
        self.label_11.setText(_translate("Form", "STOP"))
        self.label_10.setText(_translate("Form", "COW"))
        self.label_15.setText(_translate("Form", "DRN"))
        self.label_14.setText(_translate("Form", "SRN"))
        self.label_13.setText(_translate("Form", "TOOL"))
        self.label_18.setText(_translate("Form", "DNC"))
        self.label_17.setText(_translate("Form", "MSTLOCK"))
        self.label_16.setText(_translate("Form", "COOL"))
        self.label_21.setText(_translate("Form", "SBK"))
        self.label_20.setText(_translate("Form", "SKIP"))
        self.label_19.setText(_translate("Form", "DRIVE"))
        self.label_24.setText(_translate("Form", "MPG"))
        self.label_23.setText(_translate("Form", "MO1"))
        self.label_22.setText(_translate("Form", "PROTECT"))
        self.label_30.setText(_translate("Form", "OFF"))
        self.label_28.setText(_translate("Form", "ON"))
        self.Btn_GO.setText(_translate("Form", "-->"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
