# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CRT_PROG_Base.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 424)
        Form.setMinimumSize(QtCore.QSize(700, 424))
        Form.setMaximumSize(QtCore.QSize(700, 424))
        Form.setStyleSheet("background-color: rgb(192, 192, 192);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("background-color: rgb(96, 224, 224);")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setIndent(10)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setStyleSheet("")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.Lab_File_Name = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_File_Name.setFont(font)
        self.Lab_File_Name.setStyleSheet("")
        self.Lab_File_Name.setAlignment(QtCore.Qt.AlignCenter)
        self.Lab_File_Name.setObjectName("Lab_File_Name")
        self.horizontalLayout.addWidget(self.Lab_File_Name)
        self.Lab_LineNum = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_LineNum.setFont(font)
        self.Lab_LineNum.setStyleSheet("")
        self.Lab_LineNum.setAlignment(QtCore.Qt.AlignCenter)
        self.Lab_LineNum.setObjectName("Lab_LineNum")
        self.horizontalLayout.addWidget(self.Lab_LineNum)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.window_position = QtWidgets.QWidget(self.widget_2)
        self.window_position.setStyleSheet("")
        self.window_position.setObjectName("window_position")
        self.gridLayout.addWidget(self.window_position, 0, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_7 = QtWidgets.QWidget(self.widget_4)
        self.widget_7.setStyleSheet("")
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border-left: 2px solid white;\n"
"border-top: 2px solid white;\n"
"border-bottom: 2px solid rgb(140,140,140);")
        self.label_5.setIndent(5)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.Lab_Auto_FSpeed = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_Auto_FSpeed.setFont(font)
        self.Lab_Auto_FSpeed.setStyleSheet("border-top: 2px solid white;\n"
"border-bottom: 2px solid rgb(140,140,140);")
        self.Lab_Auto_FSpeed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Lab_Auto_FSpeed.setIndent(5)
        self.Lab_Auto_FSpeed.setObjectName("Lab_Auto_FSpeed")
        self.horizontalLayout_3.addWidget(self.Lab_Auto_FSpeed)
        self.label_7 = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border-right: 2px solid rgb(140,140,140);\n"
"border-top: 2px solid white;\n"
"border-bottom: 2px solid rgb(140,140,140);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout_2.addWidget(self.widget_7)
        self.widget_8 = QtWidgets.QWidget(self.widget_4)
        self.widget_8.setStyleSheet("")
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_8)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("")
        self.label_8.setIndent(2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.Lab_FSpeed = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_FSpeed.setFont(font)
        self.Lab_FSpeed.setStyleSheet("")
        self.Lab_FSpeed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Lab_FSpeed.setIndent(5)
        self.Lab_FSpeed.setObjectName("Lab_FSpeed")
        self.gridLayout_2.addWidget(self.Lab_FSpeed, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("")
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 2, 1, 1)
        self.Lab_Num = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_Num.setFont(font)
        self.Lab_Num.setStyleSheet("")
        self.Lab_Num.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Lab_Num.setIndent(10)
        self.Lab_Num.setObjectName("Lab_Num")
        self.gridLayout_2.addWidget(self.Lab_Num, 0, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("")
        self.label_9.setIndent(2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.Lab_Time_Run = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_Time_Run.setFont(font)
        self.Lab_Time_Run.setStyleSheet("")
        self.Lab_Time_Run.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Lab_Time_Run.setIndent(5)
        self.Lab_Time_Run.setObjectName("Lab_Time_Run")
        self.gridLayout_2.addWidget(self.Lab_Time_Run, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("")
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 1, 2, 1, 1)
        self.Lab_Time_Cut = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_Time_Cut.setFont(font)
        self.Lab_Time_Cut.setStyleSheet("")
        self.Lab_Time_Cut.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Lab_Time_Cut.setIndent(5)
        self.Lab_Time_Cut.setObjectName("Lab_Time_Cut")
        self.gridLayout_2.addWidget(self.Lab_Time_Cut, 1, 3, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.gridLayout_2.setColumnStretch(3, 1)
        self.gridLayout_2.setRowStretch(0, 1)
        self.gridLayout_2.setRowStretch(1, 1)
        self.verticalLayout_2.addWidget(self.widget_8)
        self.widget_9 = QtWidgets.QWidget(self.widget_4)
        self.widget_9.setStyleSheet("")
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_14 = QtWidgets.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: rgb(96, 224, 224);")
        self.label_14.setIndent(5)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_3.addWidget(self.label_14)
        self.Lab_programwindow = QtWidgets.QPlainTextEdit(self.widget_9)
        self.Lab_programwindow.setStyleSheet("background-color: rgb(255, 204, 204);\n"
"border-left: 2px solid white;\n"
"border-top: 2px solid white;\n"
"border-bottom: 2px solid rgb(140,140,140);\n"
"border-right: 2px solid rgb(140,140,140);")
        self.Lab_programwindow.setObjectName("Lab_programwindow")
        self.verticalLayout_3.addWidget(self.Lab_programwindow)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 9)
        self.verticalLayout_2.addWidget(self.widget_9)
        self.widget_10 = QtWidgets.QWidget(self.widget_4)
        self.widget_10.setStyleSheet("")
        self.widget_10.setObjectName("widget_10")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_10)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtWidgets.QLabel(self.widget_10)
        self.label_6.setStyleSheet("")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 4)
        self.label_10 = QtWidgets.QLabel(self.widget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("")
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        self.Lab_OSper = QtWidgets.QLabel(self.widget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_OSper.setFont(font)
        self.Lab_OSper.setStyleSheet("")
        self.Lab_OSper.setIndent(5)
        self.Lab_OSper.setObjectName("Lab_OSper")
        self.gridLayout_3.addWidget(self.Lab_OSper, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("")
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 1, 2, 1, 1)
        self.Lab_Lper = QtWidgets.QLabel(self.widget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_Lper.setFont(font)
        self.Lab_Lper.setStyleSheet("")
        self.Lab_Lper.setIndent(5)
        self.Lab_Lper.setObjectName("Lab_Lper")
        self.gridLayout_3.addWidget(self.Lab_Lper, 1, 3, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.gridLayout_3.setColumnStretch(2, 1)
        self.gridLayout_3.setColumnStretch(3, 1)
        self.gridLayout_3.setRowStretch(0, 1)
        self.gridLayout_3.setRowStretch(1, 1)
        self.verticalLayout_2.addWidget(self.widget_10)
        self.widget_11 = QtWidgets.QWidget(self.widget_4)
        self.widget_11.setStyleSheet("")
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Lab_Mode = QtWidgets.QLabel(self.widget_11)
        self.Lab_Mode.setMinimumSize(QtCore.QSize(0, 0))
        self.Lab_Mode.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_Mode.setFont(font)
        self.Lab_Mode.setStyleSheet("border-left: 2px solid white;\n"
"border-top: 2px solid white;\n"
"border-bottom: 2px solid rgb(140,140,140);")
        self.Lab_Mode.setAlignment(QtCore.Qt.AlignCenter)
        self.Lab_Mode.setObjectName("Lab_Mode")
        self.horizontalLayout_4.addWidget(self.Lab_Mode)
        self.label_15 = QtWidgets.QLabel(self.widget_11)
        self.label_15.setMinimumSize(QtCore.QSize(0, 0))
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("border-top: 2px solid white;\n"
"border-bottom: 2px solid rgb(140,140,140);")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_4.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.widget_11)
        self.label_16.setMinimumSize(QtCore.QSize(0, 0))
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("border-top: 2px solid white;\n"
"border-right: 2px solid black;\n"
"border-bottom: 2px solid rgb(140,140,140);")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_4.addWidget(self.label_16)
        self.Lab_EMG = QtWidgets.QLabel(self.widget_11)
        self.Lab_EMG.setMinimumSize(QtCore.QSize(0, 0))
        self.Lab_EMG.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_EMG.setFont(font)
        self.Lab_EMG.setStyleSheet("border-top: 2px solid white;\n"
"border-left: 2px solid white;\n"
"border-right: 2px solid black;\n"
"border-bottom: 2px solid rgb(140,140,140);")
        self.Lab_EMG.setAlignment(QtCore.Qt.AlignCenter)
        self.Lab_EMG.setObjectName("Lab_EMG")
        self.horizontalLayout_4.addWidget(self.Lab_EMG)
        self.Lab_ALM = QtWidgets.QLabel(self.widget_11)
        self.Lab_ALM.setMinimumSize(QtCore.QSize(0, 0))
        self.Lab_ALM.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_ALM.setFont(font)
        self.Lab_ALM.setStyleSheet("border-left: 2px solid white;\n"
"border-top: 2px solid white;\n"
"border-right: 2px solid black;\n"
"border-bottom: 2px solid rgb(140,140,140);")
        self.Lab_ALM.setAlignment(QtCore.Qt.AlignCenter)
        self.Lab_ALM.setObjectName("Lab_ALM")
        self.horizontalLayout_4.addWidget(self.Lab_ALM)
        self.Lab_Date = QtWidgets.QLabel(self.widget_11)
        self.Lab_Date.setMinimumSize(QtCore.QSize(0, 0))
        self.Lab_Date.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_Date.setFont(font)
        self.Lab_Date.setStyleSheet("border-left: 2px solid white;\n"
"border-top: 2px solid white;\n"
"border-right: 2px solid black;\n"
"border-bottom: 2px solid rgb(140,140,140);")
        self.Lab_Date.setAlignment(QtCore.Qt.AlignCenter)
        self.Lab_Date.setObjectName("Lab_Date")
        self.horizontalLayout_4.addWidget(self.Lab_Date)
        self.label_20 = QtWidgets.QLabel(self.widget_11)
        self.label_20.setMinimumSize(QtCore.QSize(0, 0))
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("border-left: 2px solid white;\n"
"border-top: 2px solid white;\n"
"border-right: 2px solid black;\n"
"border-bottom: 2px solid rgb(140,140,140);")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_4.addWidget(self.label_20)
        self.horizontalLayout_4.setStretch(0, 10)
        self.horizontalLayout_4.setStretch(1, 9)
        self.horizontalLayout_4.setStretch(2, 10)
        self.horizontalLayout_4.setStretch(3, 10)
        self.horizontalLayout_4.setStretch(4, 9)
        self.horizontalLayout_4.setStretch(5, 16)
        self.horizontalLayout_4.setStretch(6, 4)
        self.verticalLayout_2.addWidget(self.widget_11)
        self.verticalLayout_2.setStretch(0, 7)
        self.verticalLayout_2.setStretch(1, 10)
        self.verticalLayout_2.setStretch(2, 44)
        self.verticalLayout_2.setStretch(3, 10)
        self.verticalLayout_2.setStretch(4, 6)
        self.gridLayout.addWidget(self.widget_4, 0, 1, 2, 1)
        self.Lab_Modal = QtWidgets.QWidget(self.widget_2)
        self.Lab_Modal.setStyleSheet("")
        self.Lab_Modal.setObjectName("Lab_Modal")
        self.gridLayout.addWidget(self.Lab_Modal, 1, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setRowStretch(0, 3)
        self.gridLayout.setRowStretch(1, 2)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Btn_BACK = QtWidgets.QPushButton(self.widget_3)
        self.Btn_BACK.setMinimumSize(QtCore.QSize(20, 50))
        self.Btn_BACK.setMaximumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_BACK.setFont(font)
        self.Btn_BACK.setStyleSheet("color: rgb(3, 255, 255);")
        self.Btn_BACK.setText("")
        self.Btn_BACK.setObjectName("Btn_BACK")
        self.horizontalLayout_2.addWidget(self.Btn_BACK)
        self.Btn_One = CRTSoftBtn(self.widget_3)
        self.Btn_One.setMinimumSize(QtCore.QSize(65, 50))
        self.Btn_One.setMaximumSize(QtCore.QSize(65, 50))
        self.Btn_One.setStyleSheet("")
        self.Btn_One.setText("")
        self.Btn_One.setCheckable(True)
        self.Btn_One.setObjectName("Btn_One")
        self.horizontalLayout_2.addWidget(self.Btn_One)
        self.Btn_Two = CRTSoftBtn(self.widget_3)
        self.Btn_Two.setMinimumSize(QtCore.QSize(65, 50))
        self.Btn_Two.setMaximumSize(QtCore.QSize(65, 50))
        self.Btn_Two.setStyleSheet("")
        self.Btn_Two.setText("")
        self.Btn_Two.setCheckable(True)
        self.Btn_Two.setObjectName("Btn_Two")
        self.horizontalLayout_2.addWidget(self.Btn_Two)
        self.Btn_Three = CRTSoftBtn(self.widget_3)
        self.Btn_Three.setMinimumSize(QtCore.QSize(65, 50))
        self.Btn_Three.setMaximumSize(QtCore.QSize(65, 50))
        self.Btn_Three.setStyleSheet("")
        self.Btn_Three.setText("")
        self.Btn_Three.setCheckable(True)
        self.Btn_Three.setObjectName("Btn_Three")
        self.horizontalLayout_2.addWidget(self.Btn_Three)
        self.Btn_Four = CRTSoftBtn(self.widget_3)
        self.Btn_Four.setMinimumSize(QtCore.QSize(65, 50))
        self.Btn_Four.setMaximumSize(QtCore.QSize(65, 50))
        self.Btn_Four.setStyleSheet("")
        self.Btn_Four.setText("")
        self.Btn_Four.setCheckable(True)
        self.Btn_Four.setObjectName("Btn_Four")
        self.horizontalLayout_2.addWidget(self.Btn_Four)
        self.Btn_Five = CRTSoftBtn(self.widget_3)
        self.Btn_Five.setMinimumSize(QtCore.QSize(65, 50))
        self.Btn_Five.setMaximumSize(QtCore.QSize(65, 50))
        self.Btn_Five.setStyleSheet("")
        self.Btn_Five.setText("")
        self.Btn_Five.setCheckable(True)
        self.Btn_Five.setObjectName("Btn_Five")
        self.horizontalLayout_2.addWidget(self.Btn_Five)
        self.Btn_Six = CRTSoftBtn(self.widget_3)
        self.Btn_Six.setMinimumSize(QtCore.QSize(65, 50))
        self.Btn_Six.setMaximumSize(QtCore.QSize(65, 50))
        self.Btn_Six.setStyleSheet("")
        self.Btn_Six.setText("")
        self.Btn_Six.setCheckable(True)
        self.Btn_Six.setObjectName("Btn_Six")
        self.horizontalLayout_2.addWidget(self.Btn_Six)
        self.Btn_Seven = CRTSoftBtn(self.widget_3)
        self.Btn_Seven.setMinimumSize(QtCore.QSize(65, 50))
        self.Btn_Seven.setMaximumSize(QtCore.QSize(65, 50))
        self.Btn_Seven.setStyleSheet("")
        self.Btn_Seven.setText("")
        self.Btn_Seven.setCheckable(True)
        self.Btn_Seven.setObjectName("Btn_Seven")
        self.horizontalLayout_2.addWidget(self.Btn_Seven)
        self.Btn_Eight = CRTSoftBtn(self.widget_3)
        self.Btn_Eight.setMinimumSize(QtCore.QSize(65, 50))
        self.Btn_Eight.setMaximumSize(QtCore.QSize(65, 50))
        self.Btn_Eight.setStyleSheet("")
        self.Btn_Eight.setText("")
        self.Btn_Eight.setCheckable(True)
        self.Btn_Eight.setObjectName("Btn_Eight")
        self.horizontalLayout_2.addWidget(self.Btn_Eight)
        self.Btn_Nine = CRTSoftBtn(self.widget_3)
        self.Btn_Nine.setMinimumSize(QtCore.QSize(65, 50))
        self.Btn_Nine.setMaximumSize(QtCore.QSize(65, 50))
        self.Btn_Nine.setStyleSheet("")
        self.Btn_Nine.setText("")
        self.Btn_Nine.setCheckable(True)
        self.Btn_Nine.setObjectName("Btn_Nine")
        self.horizontalLayout_2.addWidget(self.Btn_Nine)
        self.Btn_Ten = CRTSoftBtn(self.widget_3)
        self.Btn_Ten.setMinimumSize(QtCore.QSize(65, 50))
        self.Btn_Ten.setMaximumSize(QtCore.QSize(65, 50))
        self.Btn_Ten.setStyleSheet("")
        self.Btn_Ten.setText("")
        self.Btn_Ten.setCheckable(True)
        self.Btn_Ten.setObjectName("Btn_Ten")
        self.horizontalLayout_2.addWidget(self.Btn_Ten)
        self.Btn_GO = QtWidgets.QPushButton(self.widget_3)
        self.Btn_GO.setMinimumSize(QtCore.QSize(20, 50))
        self.Btn_GO.setMaximumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_GO.setFont(font)
        self.Btn_GO.setStyleSheet("color: rgb(3, 255, 255);")
        self.Btn_GO.setText("")
        self.Btn_GO.setObjectName("Btn_GO")
        self.horizontalLayout_2.addWidget(self.Btn_GO)
        self.verticalLayout.addWidget(self.widget_3)
        self.verticalLayout.setStretch(0, 5)
        self.verticalLayout.setStretch(1, 71)
        self.verticalLayout.setStretch(2, 10)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "程式"))
        self.Lab_File_Name.setText(_translate("Form", "O0001"))
        self.Lab_LineNum.setText(_translate("Form", "N00000"))
        self.label_5.setText(_translate("Form", "F"))
        self.Lab_Auto_FSpeed.setText(_translate("Form", "0"))
        self.label_7.setText(_translate("Form", "MM/分"))
        self.label_8.setText(_translate("Form", "JOG F"))
        self.Lab_FSpeed.setText(_translate("Form", "0 MM/分"))
        self.label_12.setText(_translate("Form", "加工产品数"))
        self.Lab_Num.setText(_translate("Form", "1"))
        self.label_9.setText(_translate("Form", "运行时间"))
        self.Lab_Time_Run.setText(_translate("Form", "0H00M"))
        self.label_13.setText(_translate("Form", "切削时间"))
        self.Lab_Time_Cut.setText(_translate("Form", "0H00M00S"))
        self.label_14.setText(_translate("Form", "程序"))
        self.label_10.setText(_translate("Form", "OS"))
        self.Lab_OSper.setText(_translate("Form", "50%"))
        self.label_11.setText(_translate("Form", "L"))
        self.Lab_Lper.setText(_translate("Form", "100%"))
        self.Lab_Mode.setText(_translate("Form", "REF"))
        self.label_15.setText(_translate("Form", "***"))
        self.label_16.setText(_translate("Form", "***"))
        self.Lab_EMG.setText(_translate("Form", "EMG"))
        self.Lab_ALM.setText(_translate("Form", "***"))
        self.Lab_Date.setText(_translate("Form", "14:18:25"))
from CRT_Soft_Btn import CRTSoftBtn


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
