# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CRT_Pos_Absolute.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(700, 424)
        Form.setMinimumSize(QtCore.QSize(700, 424))
        Form.setMaximumSize(QtCore.QSize(700, 424))
        Form.setStyleSheet("background-color: rgb(192, 192, 192);")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("background-color: rgb(96, 224, 224);")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setIndent(5)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setStyleSheet("")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.Lab_File_Name = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_File_Name.setFont(font)
        self.Lab_File_Name.setAlignment(QtCore.Qt.AlignCenter)
        self.Lab_File_Name.setObjectName("Lab_File_Name")
        self.horizontalLayout.addWidget(self.Lab_File_Name)
        self.Lab_LineNum = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_LineNum.setFont(font)
        self.Lab_LineNum.setAlignment(QtCore.Qt.AlignCenter)
        self.Lab_LineNum.setObjectName("Lab_LineNum")
        self.horizontalLayout.addWidget(self.Lab_LineNum)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 2)
        self.window_position = QtWidgets.QWidget(Form)
        self.window_position.setStyleSheet("")
        self.window_position.setObjectName("window_position")
        self.gridLayout.addWidget(self.window_position, 1, 0, 1, 2)
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_7 = QtWidgets.QWidget(self.widget_3)
        self.widget_7.setStyleSheet("")
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_3.addWidget(self.widget_7)
        self.widget_8 = QtWidgets.QWidget(self.widget_3)
        self.widget_8.setStyleSheet("")
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border-top:2px solid white;\n"
"border-bottom:2px solid white;\n"
"border-left:2px solid white;")
        self.label_5.setIndent(5)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.Lab_Auto_FSpeed = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_Auto_FSpeed.setFont(font)
        self.Lab_Auto_FSpeed.setStyleSheet("border-top:2px solid white;\n"
"border-bottom:2px solid white;")
        self.Lab_Auto_FSpeed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Lab_Auto_FSpeed.setObjectName("Lab_Auto_FSpeed")
        self.horizontalLayout_4.addWidget(self.Lab_Auto_FSpeed)
        self.label_7 = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border-top:2px solid white;\n"
"border-bottom:2px solid white;\n"
"border-right:2px solid white;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.horizontalLayout_3.addWidget(self.widget_8)
        self.gridLayout.addWidget(self.widget_3, 2, 0, 1, 2)
        self.Lab_Modal = QtWidgets.QWidget(Form)
        self.Lab_Modal.setStyleSheet("")
        self.Lab_Modal.setObjectName("Lab_Modal")
        self.gridLayout.addWidget(self.Lab_Modal, 3, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(Form)
        self.widget_5.setStyleSheet("")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_9 = QtWidgets.QWidget(self.widget_5)
        self.widget_9.setStyleSheet("")
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_11 = QtWidgets.QWidget(self.widget_9)
        self.widget_11.setStyleSheet("")
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.widget_11)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.Lab_FSpeed = QtWidgets.QLabel(self.widget_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_FSpeed.setFont(font)
        self.Lab_FSpeed.setStyleSheet("")
        self.Lab_FSpeed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Lab_FSpeed.setIndent(8)
        self.Lab_FSpeed.setObjectName("Lab_FSpeed")
        self.horizontalLayout_6.addWidget(self.Lab_FSpeed)
        self.label_12 = QtWidgets.QLabel(self.widget_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("")
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.Lab_Num = QtWidgets.QLabel(self.widget_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_Num.setFont(font)
        self.Lab_Num.setStyleSheet("")
        self.Lab_Num.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Lab_Num.setObjectName("Lab_Num")
        self.horizontalLayout_6.addWidget(self.Lab_Num)
        self.verticalLayout_2.addWidget(self.widget_11)
        self.widget_12 = QtWidgets.QWidget(self.widget_9)
        self.widget_12.setStyleSheet("")
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.widget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("")
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.Lab_Time_Run = QtWidgets.QLabel(self.widget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_Time_Run.setFont(font)
        self.Lab_Time_Run.setStyleSheet("")
        self.Lab_Time_Run.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Lab_Time_Run.setIndent(8)
        self.Lab_Time_Run.setObjectName("Lab_Time_Run")
        self.horizontalLayout_7.addWidget(self.Lab_Time_Run)
        self.label_15 = QtWidgets.QLabel(self.widget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("")
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_7.addWidget(self.label_15)
        self.Lab_Time_Cut = QtWidgets.QLabel(self.widget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_Time_Cut.setFont(font)
        self.Lab_Time_Cut.setStyleSheet("")
        self.Lab_Time_Cut.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Lab_Time_Cut.setObjectName("Lab_Time_Cut")
        self.horizontalLayout_7.addWidget(self.Lab_Time_Cut)
        self.verticalLayout_2.addWidget(self.widget_12)
        self.widget_13 = QtWidgets.QWidget(self.widget_9)
        self.widget_13.setStyleSheet("")
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_2.addWidget(self.widget_13)
        self.widget_14 = QtWidgets.QWidget(self.widget_9)
        self.widget_14.setStyleSheet("")
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_2.addWidget(self.widget_14)
        self.widget_15 = QtWidgets.QWidget(self.widget_9)
        self.widget_15.setStyleSheet("")
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_15)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_17 = QtWidgets.QLabel(self.widget_15)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("")
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_8.addWidget(self.label_17)
        self.Lab_OSper = QtWidgets.QLabel(self.widget_15)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_OSper.setFont(font)
        self.Lab_OSper.setStyleSheet("")
        self.Lab_OSper.setIndent(5)
        self.Lab_OSper.setObjectName("Lab_OSper")
        self.horizontalLayout_8.addWidget(self.Lab_OSper)
        self.label_19 = QtWidgets.QLabel(self.widget_15)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("")
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_8.addWidget(self.label_19)
        self.Lab_Lper = QtWidgets.QLabel(self.widget_15)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_Lper.setFont(font)
        self.Lab_Lper.setStyleSheet("")
        self.Lab_Lper.setIndent(5)
        self.Lab_Lper.setObjectName("Lab_Lper")
        self.horizontalLayout_8.addWidget(self.Lab_Lper)
        self.verticalLayout_2.addWidget(self.widget_15)
        self.verticalLayout.addWidget(self.widget_9)
        self.widget_10 = QtWidgets.QWidget(self.widget_5)
        self.widget_10.setStyleSheet("background-color: rgb(0,0,0);")
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_5.setContentsMargins(1, 0, 1, 0)
        self.horizontalLayout_5.setSpacing(1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Lab_Mode = QtWidgets.QLabel(self.widget_10)
        self.Lab_Mode.setMinimumSize(QtCore.QSize(50, 0))
        self.Lab_Mode.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_Mode.setFont(font)
        self.Lab_Mode.setStyleSheet("background-color: rgb(192, 192, 192);")
        self.Lab_Mode.setAlignment(QtCore.Qt.AlignCenter)
        self.Lab_Mode.setObjectName("Lab_Mode")
        self.horizontalLayout_5.addWidget(self.Lab_Mode)
        self.label_9 = QtWidgets.QLabel(self.widget_10)
        self.label_9.setMinimumSize(QtCore.QSize(45, 0))
        self.label_9.setMaximumSize(QtCore.QSize(45, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(192, 192, 192);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.widget_10)
        self.label_10.setMinimumSize(QtCore.QSize(50, 0))
        self.label_10.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(192, 192, 192);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.Lab_EMG = QtWidgets.QLabel(self.widget_10)
        self.Lab_EMG.setMinimumSize(QtCore.QSize(50, 0))
        self.Lab_EMG.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_EMG.setFont(font)
        self.Lab_EMG.setStyleSheet("background-color: rgb(192, 192, 192);")
        self.Lab_EMG.setAlignment(QtCore.Qt.AlignCenter)
        self.Lab_EMG.setObjectName("Lab_EMG")
        self.horizontalLayout_5.addWidget(self.Lab_EMG)
        self.Lab_ALM = QtWidgets.QLabel(self.widget_10)
        self.Lab_ALM.setMinimumSize(QtCore.QSize(45, 0))
        self.Lab_ALM.setMaximumSize(QtCore.QSize(45, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_ALM.setFont(font)
        self.Lab_ALM.setStyleSheet("background-color: rgb(192, 192, 192);")
        self.Lab_ALM.setAlignment(QtCore.Qt.AlignCenter)
        self.Lab_ALM.setObjectName("Lab_ALM")
        self.horizontalLayout_5.addWidget(self.Lab_ALM)
        self.Lab_Date = QtWidgets.QLabel(self.widget_10)
        self.Lab_Date.setMinimumSize(QtCore.QSize(82, 0))
        self.Lab_Date.setMaximumSize(QtCore.QSize(82, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_Date.setFont(font)
        self.Lab_Date.setStyleSheet("background-color: rgb(192, 192, 192);")
        self.Lab_Date.setAlignment(QtCore.Qt.AlignCenter)
        self.Lab_Date.setObjectName("Lab_Date")
        self.horizontalLayout_5.addWidget(self.Lab_Date)
        self.label_14 = QtWidgets.QLabel(self.widget_10)
        self.label_14.setMinimumSize(QtCore.QSize(18, 0))
        self.label_14.setMaximumSize(QtCore.QSize(18, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: rgb(192, 192, 192);")
        self.label_14.setText("")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_5.addWidget(self.label_14)
        self.verticalLayout.addWidget(self.widget_10)
        self.verticalLayout.setStretch(0, 5)
        self.verticalLayout.setStretch(1, 1)
        self.gridLayout.addWidget(self.widget_5, 3, 1, 1, 1)
        self.widget_6 = QtWidgets.QWidget(Form)
        self.widget_6.setStyleSheet("")
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Btn_BACK = QtWidgets.QPushButton(self.widget_6)
        self.Btn_BACK.setMinimumSize(QtCore.QSize(20, 50))
        self.Btn_BACK.setMaximumSize(QtCore.QSize(20, 50))
        self.Btn_BACK.setSizeIncrement(QtCore.QSize(0, 0))
        self.Btn_BACK.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_BACK.setFont(font)
        self.Btn_BACK.setStyleSheet("color: rgb(3, 255, 255);")
        self.Btn_BACK.setText("")
        self.Btn_BACK.setObjectName("Btn_BACK")
        self.horizontalLayout_2.addWidget(self.Btn_BACK)
        self.Btn_One = CRTSoftBtn(self.widget_6)
        self.Btn_One.setMinimumSize(QtCore.QSize(65, 50))
        self.Btn_One.setMaximumSize(QtCore.QSize(65, 50))
        self.Btn_One.setStyleSheet("")
        self.Btn_One.setText("")
        self.Btn_One.setCheckable(True)
        self.Btn_One.setObjectName("Btn_One")
        self.horizontalLayout_2.addWidget(self.Btn_One)
        self.Btn_Two = CRTSoftBtn(self.widget_6)
        self.Btn_Two.setMinimumSize(QtCore.QSize(65, 50))
        self.Btn_Two.setMaximumSize(QtCore.QSize(65, 50))
        self.Btn_Two.setStyleSheet("")
        self.Btn_Two.setText("")
        self.Btn_Two.setCheckable(True)
        self.Btn_Two.setObjectName("Btn_Two")
        self.horizontalLayout_2.addWidget(self.Btn_Two)
        self.Btn_Three = CRTSoftBtn(self.widget_6)
        self.Btn_Three.setMinimumSize(QtCore.QSize(65, 50))
        self.Btn_Three.setMaximumSize(QtCore.QSize(65, 50))
        self.Btn_Three.setStyleSheet("")
        self.Btn_Three.setText("")
        self.Btn_Three.setCheckable(True)
        self.Btn_Three.setObjectName("Btn_Three")
        self.horizontalLayout_2.addWidget(self.Btn_Three)
        self.Btn_Four = CRTSoftBtn(self.widget_6)
        self.Btn_Four.setMinimumSize(QtCore.QSize(65, 50))
        self.Btn_Four.setMaximumSize(QtCore.QSize(65, 50))
        self.Btn_Four.setStyleSheet("")
        self.Btn_Four.setText("")
        self.Btn_Four.setCheckable(True)
        self.Btn_Four.setObjectName("Btn_Four")
        self.horizontalLayout_2.addWidget(self.Btn_Four)
        self.Btn_Five = CRTSoftBtn(self.widget_6)
        self.Btn_Five.setMinimumSize(QtCore.QSize(65, 50))
        self.Btn_Five.setMaximumSize(QtCore.QSize(65, 50))
        self.Btn_Five.setStyleSheet("")
        self.Btn_Five.setText("")
        self.Btn_Five.setCheckable(True)
        self.Btn_Five.setObjectName("Btn_Five")
        self.horizontalLayout_2.addWidget(self.Btn_Five)
        self.Btn_Six = CRTSoftBtn(self.widget_6)
        self.Btn_Six.setMinimumSize(QtCore.QSize(65, 50))
        self.Btn_Six.setMaximumSize(QtCore.QSize(65, 50))
        self.Btn_Six.setStyleSheet("")
        self.Btn_Six.setText("")
        self.Btn_Six.setCheckable(True)
        self.Btn_Six.setObjectName("Btn_Six")
        self.horizontalLayout_2.addWidget(self.Btn_Six)
        self.Btn_Seven = CRTSoftBtn(self.widget_6)
        self.Btn_Seven.setMinimumSize(QtCore.QSize(65, 50))
        self.Btn_Seven.setMaximumSize(QtCore.QSize(65, 50))
        self.Btn_Seven.setStyleSheet("")
        self.Btn_Seven.setText("")
        self.Btn_Seven.setCheckable(True)
        self.Btn_Seven.setObjectName("Btn_Seven")
        self.horizontalLayout_2.addWidget(self.Btn_Seven)
        self.Btn_Eight = CRTSoftBtn(self.widget_6)
        self.Btn_Eight.setMinimumSize(QtCore.QSize(65, 50))
        self.Btn_Eight.setMaximumSize(QtCore.QSize(65, 50))
        self.Btn_Eight.setStyleSheet("")
        self.Btn_Eight.setText("")
        self.Btn_Eight.setCheckable(True)
        self.Btn_Eight.setObjectName("Btn_Eight")
        self.horizontalLayout_2.addWidget(self.Btn_Eight)
        self.Btn_Nine = CRTSoftBtn(self.widget_6)
        self.Btn_Nine.setMinimumSize(QtCore.QSize(65, 50))
        self.Btn_Nine.setMaximumSize(QtCore.QSize(65, 50))
        self.Btn_Nine.setStyleSheet("")
        self.Btn_Nine.setText("")
        self.Btn_Nine.setCheckable(True)
        self.Btn_Nine.setObjectName("Btn_Nine")
        self.horizontalLayout_2.addWidget(self.Btn_Nine)
        self.Btn_Ten = CRTSoftBtn(self.widget_6)
        self.Btn_Ten.setMinimumSize(QtCore.QSize(65, 50))
        self.Btn_Ten.setMaximumSize(QtCore.QSize(65, 50))
        self.Btn_Ten.setStyleSheet("")
        self.Btn_Ten.setText("")
        self.Btn_Ten.setCheckable(True)
        self.Btn_Ten.setObjectName("Btn_Ten")
        self.horizontalLayout_2.addWidget(self.Btn_Ten)
        self.Btn_GO = QtWidgets.QPushButton(self.widget_6)
        self.Btn_GO.setMinimumSize(QtCore.QSize(20, 50))
        self.Btn_GO.setMaximumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_GO.setFont(font)
        self.Btn_GO.setStyleSheet("color: rgb(3, 255, 255);")
        self.Btn_GO.setText("")
        self.Btn_GO.setObjectName("Btn_GO")
        self.horizontalLayout_2.addWidget(self.Btn_GO)
        self.gridLayout.addWidget(self.widget_6, 4, 0, 1, 2)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setRowStretch(0, 5)
        self.gridLayout.setRowStretch(1, 34)
        self.gridLayout.setRowStretch(2, 6)
        self.gridLayout.setRowStretch(3, 31)
        self.gridLayout.setRowStretch(4, 10)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "现在位置"))
        self.Lab_File_Name.setText(_translate("Form", "O0000"))
        self.Lab_LineNum.setText(_translate("Form", "N00000"))
        self.label_5.setText(_translate("Form", "F"))
        self.Lab_Auto_FSpeed.setText(_translate("Form", "0"))
        self.label_7.setText(_translate("Form", "MM/分"))
        self.label_8.setText(_translate("Form", "JOG F"))
        self.Lab_FSpeed.setText(_translate("Form", "0 MM/分"))
        self.label_12.setText(_translate("Form", "加工产品数"))
        self.Lab_Num.setText(_translate("Form", "1"))
        self.label_11.setText(_translate("Form", "运行时间"))
        self.Lab_Time_Run.setText(_translate("Form", "00H00M"))
        self.label_15.setText(_translate("Form", "切削时间"))
        self.Lab_Time_Cut.setText(_translate("Form", "00H00M00S"))
        self.label_17.setText(_translate("Form", "OS"))
        self.Lab_OSper.setText(_translate("Form", "50%"))
        self.label_19.setText(_translate("Form", "L"))
        self.Lab_Lper.setText(_translate("Form", "100%"))
        self.Lab_Mode.setText(_translate("Form", "REF"))
        self.label_9.setText(_translate("Form", "***"))
        self.label_10.setText(_translate("Form", "***"))
        self.Lab_EMG.setText(_translate("Form", "EMG"))
        self.Lab_ALM.setText(_translate("Form", "***"))
        self.Lab_Date.setText(_translate("Form", "14:18:25"))
from CRT_Soft_Btn import CRTSoftBtn


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
